In [1]:
!pip install ctgan

Collecting ctgan
  Downloading ctgan-0.10.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: tqdm<5,>=4.29 in /usr/local/lib/python3.10/dist-packages (from ctgan) (4.66.6)
Collecting rdt>=1.11.0 (from ctgan)
  Downloading rdt-1.13.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from ctgan) (2.2.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from ctgan) (2.5.1+cu121)
Requirement already satisfied: numpy>=1.23.3 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->ctgan) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->ctgan) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->ctgan) (2024.2)
Collecting Faker>=17 (from rdt>=1.11.0->ctgan)
  Downloading Faker-33.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from rdt>=1.11.0->ctgan) (1.5.2)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from rdt>=1.11.0->ctgan) (1.13.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->ctgan) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->ctgan) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.11.0->ctgan) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.11.0->ctgan) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->ctgan) (3.0.2)
Downloading ctgan-0.10.2-py3-none-any.whl (23 kB)
Downloading rdt-1.13.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 5.4 MB/s eta 0:00:00
Downloading Faker-33.0.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 46.4 MB/s eta 0:00:00
Installing collected packages: Faker, rdt, ctgan
Successfully installed Faker-33.0.0 ctgan-0.10.2 rdt-1.13.1

In [2]:
import pandas as pd
from ctgan import CTGAN
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', header=None)
data.columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',
    'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income'
]
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
categorical_columns = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'income']
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col].astype(str))
    label_encoders[col] = le

In [7]:
model = CTGAN(epochs=5)
model.fit(data, discrete_columns=categorical_columns)

In [8]:
synthetic_data = model.sample(n=len(data))

In [9]:
print("Real Data Sample:")
print(data.head())
print("\nSynthetic Data Sample:")
print(synthetic_data.head())

Real Data Sample:
   age  workclass  fnlwgt  education  education-num  marital-status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours-per-week  native-country  income
0              40              39       0
1              13              39       0
2              40              39       0
3              40              39       0
4              40               5       0

Synthetic Data Sample:
   age  workclass  fnlwgt  education  education-num  marital-status  \
0   62          4  409673         11             10               4
1   37          2  237839         15              3               4
2   37          4  373867         14              2               4
3   53          4  243096          2             10               2
4   51          6   47170         15              9               5

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           3             1     4    0            23             6
1           3             1     4    0            46             3
2           3             0     4    1             5            -2
3           1             3     4    0            49             2
4           0             1     4    0            69             2

   hours-per-week  native-country  income
0              66              39       1
1              14              39       0
2              40              39       1
3              53              19       0
4              52              39       0